debug: true
server:
  port: 8080
  contextPath: /
spring:
 application:
  name: App1

security:
  user:
    password: user
  ignored: /,/favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /admin/login
management:
  security:
    role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'
---
spring:
  profiles: default
security:
  oauth2:
    client:
      clientId: a1d5fb3fa0c879b93528
      clientSecret: 9020171b55abb5caed14615789ff8415c955e1b2
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
---

spring:
  profiles: ownserver
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      clientId: clientid01
      clientSecret: mysecret
    resource:
       userInfoUri: http://localhost:8081/user


